import type { NextPage } from "next";
import Head from "next/head";
import { Col, Row } from "antd";
import Menu from "@/components/Menu";
import styles from "../styles/home.module.less";
import "antd/dist/antd.css";
import Statistics from "@/components/Chart/Statistic";
import Rank from "@/components/Chart/Rank";
import userIcon from "@/assets/user";
import doctorIcon from "@/assets/doctor";
import teacherIcon from "@/assets/teacher";
import Flex from "@/components/Flex";
import { hotCourseList, cmpltCourseList } from "@/mock/couseRank";

console.log("styles: ", styles);
const Home: NextPage = () => {
  return (
    <Flex className={styles.layout}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className={styles.main}>
        <h2 className={styles.title}>Carto Journey Dashboard</h2>

        <Row gutter={20}>
          <Col className="gutter-row" span={18}>
            <Row gutter={20}>
              <Col className="gutter-row" span={8}>
                <Statistics name="总注册学员" value="3500" icon={userIcon} />
              </Col>
              <Col className="gutter-row" span={8}>
                <Statistics
                  name="总注册目标术者"
                  value="480"
                  icon={doctorIcon}
                />
              </Col>
              <Col className="gutter-row" span={8}>
                <Statistics name="总注册导师" value="54" icon={teacherIcon} />
              </Col>
            </Row>
          </Col>
          <Col className="gutter-row" span={6}>
            <Rank
              ranklists={[
                { title: "最热门课程top10", data: hotCourseList },
                { title: "完播课程top10", data: cmpltCourseList },
              ]}
            />
          </Col>
        </Row>
      </main>
    </Flex>
  );
};

export default Home;
